### ISSUE TITLE
Add contributing setup info to the README

### ISSUE THREAD

**Issue by adierkens** [intuit/proof#13]
When running the `proof` repo locally, you must use `yarn` because proof uses `yarn workspaces` internally. This info is documented in the [CONTRIBUTING.md](https://github.com/intuit/proof/blob/master/CONTRIBUTING.md#getting-started) but it should also be in the README.

**Comment by amreshk005** [comment]
@adierkens is this is still open? if yes can I work on this?

**Comment by digikin** [comment]
ill take it

**Comment by adierkens** [comment]
Fixed by https://github.com/intuit/proof/pull/14
