### ISSUE TITLE
When ran from component level no test picked up

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/proof#26]
I have a test in a monorepo component/package:

When running `proof` from the component directory, no test is picked up. 
When run from root of project, test is piked up

**Comment by 20harshita** [comment]
can i look into this issue ?

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/intuit/proof/releases/tag/v0.1.0) :rocket:
