### ISSUE TITLE
Some warnings should be errors

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/proof#27]
I got the following warning when a story didn't exits

```
⚠  warning      No storybook kind found for Components|Left Navigation in /Users/alisowski/Documents/cgds/components/SkipToContent/__automation__/SkipToContent.proof.ts
```

This should really be an error, since the test won't get run.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/intuit/proof/releases/tag/v0.1.0) :rocket:
