### ISSUE TITLE
Hook Documentation

### ISSUE THREAD

**Issue by adierkens** [intuit/proof#3]
Most of the docs focus around usage, but documenting the hooks that each package exposes would be _super_ helpful

**Comment by ajaykgp** [comment]
I would like to take this up.

**Comment by adierkens** [comment]
Awesome! Let me know if you need any help with it

**Comment by shubhampkj** [comment]
Hi @adierkens ,
Is this still open and up for grabs? I would like to take this up during HacktoberFest '20.
Please do let me know.

**Comment by adierkens** [comment]
@shubhampkj Yeah feel free to work on it and put up a PR

**Comment by nsinghal12** [comment]
@adierkens I have raised PR #68 for this issue. Let me know your thoughts if more information is required.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v0.1.6`](https://github.com/intuit/proof/releases/tag/v0.1.6) :rocket:
