### ISSUE TITLE
Change Selenium Port

### ISSUE THREAD

**Issue by hainessss** [intuit/proof#44]
Is there a way to provide a different port for selenium to run on besides 4444?

**Comment by adierkens** [comment]
We fall back to the `gridOptions.local` in the config if one is passed in, but it doesn't look like we use that to start the local grid up. 

If you're open to adding a PR, it should be as simple as calculating the options first, then using that port when starting the local server: https://github.com/intuit/proof/blob/master/packages/browser/src/main.ts#L127

I can try to put up a PR later too

**Comment by hainessss** [comment]
Yeah I noticed that as well.  I may have time today to do a PR.

**Comment by hainessss** [comment]
Fixed by #45  released in v0.0.18
