### ISSUE TITLE
Add documentation for getting started with custom plugins

### ISSUE THREAD

**Issue by adierkens** [intuit/proof#63]
While we have many plugins to use as implementation examples, I'd like the documentation to also have an on-boarding guide to writing a custom plugin

**Comment by nsinghal12** [comment]
@adierkens I'd like to work on this.

**Comment by nsinghal12** [comment]
@adierkens I have raised PR #67  to gather early feedback to see if there are directional changes required.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v0.1.6`](https://github.com/intuit/proof/releases/tag/v0.1.6) :rocket:

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v0.1.6`](https://github.com/intuit/proof/releases/tag/v0.1.6) :rocket:
