### ISSUE TITLE
Project READMEs

### ISSUE THREAD

**Issue by adierkens** [intuit/proof#7]
Add READMEs to each of the plugins/packages so they show up in the npm docs.

Most of the packages don't have any `README.md` files in them, so when they [get published to `npm`](https://www.npmjs.com/package/@proof-ui/console-plugin
), no docs show up.

There is [some documentation](https://intuit.github.io/proof/#/./plugins/console) for the `plugins` that can serve as a starting point which is created from [here](https://github.com/intuit/proof/blob/master/packages/docs/src/plugins/console.md)

Ideally, the docs served on github-pages would match that of the `README`'s in each project, and would simply pull them in via a build-step before publishing the docs.

**Comment by wolfhoundjesse** [comment]
I can start on this. 😀

**Comment by 20harshita** [comment]
I am new to open source . please assign this on my name .

**Comment by hunarjain007** [comment]
@adierkens 
Hey,
 I want to contribute on this issue.

**Comment by adierkens** [comment]
Thanks for the interest. No need to comment first, feel free to just open up a PR with the changes

**Comment by kbaumzie** [comment]
Hi there! I did some research about your last requirement: 

> Ideally, the docs served on github-pages would match that of the README's in each project, and would simply pull them in via a build-step before publishing the docs.

It looks like since you have gh-pages sourcing your documentation site, it only reads from the /docs folder and there isn't a way to intercept this. If you want all the readme's to be synced with the contents of the /docs folder, I think you have to manually go in to update them. (I could be wrong but this is what I've found online).

**Comment by adierkens** [comment]
I was thinking of more of a build step that would copy each projects README into docs before publishing to gh-pages

**Comment by cagoncil** [comment]
Apologies for the simple question. I'm extremely new to GitHub, but would love to contribute to this issue. Is there a specific location you would prefer the README files to go into? I see that there are several README files in this [plugins folder](https://github.com/intuit/proof/tree/master/packages/docs/src/plugins) - is this where we should put them? Or (and/or) would you like us to add the README files directly to each package folder that is currently missing a README file (e.g., [this](https://github.com/intuit/proof/tree/master/packages/storybook) package folder)? Thanks in advance, can't wait to participate in tonight's Hacktoberfest event.

**Comment by adierkens** [comment]
:rocket: Issue was released in v0.0.8 :rocket:
