### ISSUE TITLE
CLI not respecting config arg

### ISSUE THREAD

**Issue by hainessss** [intuit/proof#70]
Hello team.

I am running proof as such: `yarn proof --url https://url.com/ --remote --config ./.ci/proof-chrome.config.js`. But, proof ignores `proof-chrome.config.js` and instead uses `proof.config.js` which resides in the root of the project. 

expectation: proof uses the passed config.

Thanks,

**Comment by adierkens** [comment]
Thanks for the issue, I’ll take a look

**Comment by hainessss** [comment]
Were you able to reproduce this? @adierkens

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v0.1.6`](https://github.com/intuit/proof/releases/tag/v0.1.6) :rocket:

**Comment by hainessss** [comment]
I think this issue still exists. I see the custom path being passed to cosmicConfig but the result ends up being the one in the root.  maybe the later array elements in `searchPlaces` wins out?
